# Standard pipeline build.  I skip most of the stages because 
# this is a demo app and those stages just slow down the build
# and cause other gratuitous headaches.
#
# This deploys to App Engine as xbblm0l.contacts.app on nonprod11

include:
  - project: 'glb/glb-01/gl-templates'
    ref: master
    file: '/gitlab-ci/java8-ci-common-core.yml'

.defendbot_scan:
  script:
    - echo "Skipping defendbot scan"
  tags:
    - jdk8-support

variables:
    ENABLE_AE_DEPLOYMENT: "no"
    GLB_COMMON_TEST_NO_SONAR: "yes"
    GLB_COMMON_NO_NEXUSIQ: "yes"
    SKIP_MRP_RELEASE: "yes" 